import { showDirectoryPicker } from './showDirectoryPicker.js';
import { showOpenFilePicker } from './showOpenFilePicker.js';
import { showSaveFilePicker } from './showSaveFilePicker.js';
import { getOriginPrivateDirectory } from './getOriginPrivateDirectory.js';
import { FileSystemDirectoryHandle } from './FileSystemDirectoryHandle.js';
import { FileSystemFileHandle } from './FileSystemFileHandle.js';
import { FileSystemHandle } from './FileSystemHandle.js';
import { support } from './support.js';
declare const polyfillDataTransferItem: () => Promise<typeof import("./polyfillDataTransferItem.js")>;
declare const lazyFileSystemWritableFileStream: () => Promise<typeof import("./FileSystemWritableFileStream.js").FileSystemWritableFileStream>;
export { FileSystemDirectoryHandle, FileSystemFileHandle, FileSystemHandle, lazyFileSystemWritableFileStream, getOriginPrivateDirectory, showDirectoryPicker, showOpenFilePicker, showSaveFilePicker, polyfillDataTransferItem, support };
